repos:
#- repo: https://github.com/pablominue/pysqltools
- repo: local
  hooks:
  - id: format
    name: format
    entry: bash -c "poetry run make fmt"
    language: system
    types: []
    verbose: true

- repo: local
  hooks:
  - id: verification
    name: verification
    entry: bash -c "poetry run make verify"
    language: system
    types: []
    verbose: true